Anton/experimental fpga
codeplaysoftware/portBLAS pull request #298
Opened 2021-05-14 18:26 UTC by ShanoToni

Added modifications to the tests and benchmarks in order to use the ComputeCPP runtime fpga fix in the queue constructor.
When compiling with the SYCL_BLAS_FPGA flag the queue is constructed in the .hpp file included in the benchmark or test .cpp file so it passes in trough the compute++ compiler and has access to the new dummy kernel from the queue constructor. (Required for the FPGA)

2021-09-22 07:15 UTC, ProGTX requested changes

2021-09-22 07:15 UTC, ProGTX commented on CMakeLists.txt
> +    target_link_libraries(sycl_blas PRIVATE hipSYCL::hipSYCL-rt)
I think it'd be worth splitting out hipSYCL support and most other CMake changes (without FPGA support) into a separate PR, I believe we should be able to get that in much faster.

2021-11-19 10:08 UTC, mehdi-goli approved these changes

2021-11-19 10:19 UTC, mehdi-goli requested changes
The change in the Benchmark and test are radical, we need to find a better way to remove the queue creation

2024-06-04 09:20 UTC, Rbiessy commented
Closing as this is outdated.

2024-06-04 09:20 UTC, closed without merging